#!/usr/bin/env python3
"""
Extract point clouds from Plotly HTML files (generated by visualize_zarr_pointcloud.py)
and create a rotated visualization video for each HTML.

Produces one MP4 per HTML in the output directory.

Dependencies:
  pip install plotly kaleido numpy tqdm
Requires ffmpeg in PATH to assemble video frames.

Example:
  python html_pointclouds_to_videos.py \
    --input-dir visualizations/zarr1_pointclouds \
    --output-dir visualizations/videos_zarr1 \
    --num-frames 60 --fps 15
"""

import argparse
import json
import math
import os
import subprocess
import re
from pathlib import Path
from typing import List, Tuple

import numpy as np
import plotly.graph_objects as go
from tqdm import tqdm


def find_matching(text: str, start_idx: int, open_ch: str, close_ch: str) -> int:
    """Find matching closing bracket index in text starting at start_idx (which points to open_ch)."""
    depth = 0
    for i in range(start_idx, len(text)):
        if text[i] == open_ch:
            depth += 1
        elif text[i] == close_ch:
            depth -= 1
            if depth == 0:
                return i
    raise ValueError("No matching closing bracket found")


def extract_plotly_data_from_html(html_path: Path) -> Tuple[np.ndarray, np.ndarray, np.ndarray, List[Tuple[int,int,int]]]:
    """Extract x,y,z and rgb color list from a Plotly HTML generated by fig.write_html().

    Returns:
      x,y,z arrays (1D), colors list of (r,g,b) tuples (same length) -- rgb in 0..255
    """
    text = html_path.read_text(encoding='utf8')

    # Heuristics: try to locate Plotly data in several ways. The goal is to
    # extract a list-of-traces where each trace is a dict and contains x,y,z.

    def try_load_json(s: str):
        # light cleanup then try json.loads
        s2 = re.sub(r",\s*([\]\}])", r"\1", s)
        # replace some JS literals that are invalid JSON
        s2 = s2.replace('\n', ' ')
        s2 = re.sub(r"\bundefined\b", 'null', s2)
        s2 = re.sub(r"\bNaN\b", 'null', s2)
        s2 = re.sub(r"\bInfinity\b", 'null', s2)
        try:
            return json.loads(s2)
        except Exception:
            # fallback: try replacing single quotes -> double quotes and booleans
            s3 = s2.replace("'", '"').replace('False', 'false').replace('True', 'true')
            return json.loads(s3)


    def find_arg_array_after_call(anchor_idx: int) -> Tuple[int, int]:
        """Given index of '(' for a call, find the array-like second argument span.

        This is string-aware: it ignores brackets/parens that are inside string
        literals (single or double quoted) and handles escapes.

        Returns (start_idx, end_idx) of the array (inclusive start, exclusive end),
        or (None, None) if not found.
        """
        i = anchor_idx
        n = len(text)
        # scan forward to find the first '(' if anchor_idx points before it
        if i < n and text[i] != '(':
            i = text.find('(', i)
            if i == -1:
                return None, None

        # now parse the call arguments, tracking depth and string state
        i += 1  # move past '('
        depth = 0
        in_str = None
        esc = False
        arg_idx = 0
        arg_start = None
        while i < n:
            ch = text[i]
            if in_str:
                if esc:
                    esc = False
                elif ch == '\\':
                    esc = True
                elif ch == in_str:
                    in_str = None
            else:
                if ch == '"' or ch == "'":
                    in_str = ch
                elif ch == '(':
                    depth += 1
                elif ch == ')':
                    if depth == 0:
                        # end of call
                        break
                    depth -= 1
                elif ch == ',' and depth == 0:
                    # end of current arg at top level
                    arg_idx += 1
                    # if this is the first comma, the next arg is arg_idx==1
                    if arg_idx == 1:
                        # locate the start of the next non-space token
                        j = i + 1
                        while j < n and text[j].isspace():
                            j += 1
                        if j < n and text[j] == '[':
                            # found array start; now find matching ']' with string-awareness
                            s = j
                            k = j
                            in_str2 = None
                            esc2 = False
                            arr_depth = 0
                            while k < n:
                                c = text[k]
                                if in_str2:
                                    if esc2:
                                        esc2 = False
                                    elif c == '\\':
                                        esc2 = True
                                    elif c == in_str2:
                                        in_str2 = None
                                else:
                                    if c == '"' or c == "'":
                                        in_str2 = c
                                    elif c == '[':
                                        arr_depth += 1
                                    elif c == ']':
                                        arr_depth -= 1
                                        if arr_depth == 0:
                                            return s, k + 1
                                k += 1
                            return None, None
            i += 1
        return None, None

    data = None

    # 1) common anchors: try to locate the final Plotly.* call and extract the
    # second argument (the data array) using a string-aware parser.
    anchors = ["Plotly.newPlot(", "Plotly.react(", "Plotly.plot(", "newPlot("]
    for a in anchors:
        p = text.rfind(a)
        if p != -1:
            # p points to the start of the anchor including '('
            # find the '(' index (should be at p + len(a)-1 but be robust)
            paren_idx = text.find('(', p)
            if paren_idx == -1:
                continue
            s, e = find_arg_array_after_call(paren_idx)
            if s is not None and e is not None:
                cand = text[s:e]
                try:
                    data = try_load_json(cand)
                    break
                except Exception:
                    # try a bit of cleanup and retry
                    try:
                        cand2 = cand.replace("\n", " ")
                        data = try_load_json(cand2)
                        break
                    except Exception:
                        data = None

    # 2) try to find explicit x/y/z occurrences nearby
    if data is None:
        # look for an "x": [ ... ] and try to collect x,y,z within a local window
        m = re.search(r'(?:"x"|\'x\'|\bx\b)\s*:\s*(\[)', text)
        if m:
            # bracket for x
            off = m.start(1)
            br = find_bracketed(off)
            if br:
                sx, ex = br
                window_start = max(0, sx - 3000)
                window_end = min(len(text), ex + 3000)
                window = text[window_start:window_end]

                def extract_array_in_window(key: str):
                    mm = re.search(rf'(?:"{key}"|\'{key}\'|\b{key}\b)\s*:\s*(\[)', window)
                    if not mm:
                        return None
                    # convert window-relative index to absolute
                    abs_idx = window_start + mm.start(1)
                    br2 = find_bracketed(abs_idx)
                    if not br2:
                        return None
                    s2, e2 = br2
                    try:
                        return try_load_json(text[s2:e2])
                    except Exception:
                        return None

                x_arr = extract_array_in_window('x')
                y_arr = extract_array_in_window('y')
                z_arr = extract_array_in_window('z')
                if x_arr is not None and y_arr is not None and z_arr is not None:
                    data = [{ 'x': x_arr, 'y': y_arr, 'z': z_arr }]

    # 3) permissive numeric fallback: sometimes the data is embedded in JS expressions
    # or contains non-JSON tokens; try to locate x/y/z arrays as bracketed text and
    # extract numbers with regex (more tolerant than json.loads).
    if data is None:
        def find_bracket_span(start_idx: int):
            # string-aware bracket matcher for '[' ... ']' starting at start_idx
            n = len(text)
            if start_idx >= n or text[start_idx] != '[':
                return None
            i = start_idx
            in_s = None
            esc = False
            depth = 0
            while i < n:
                c = text[i]
                if in_s:
                    if esc:
                        esc = False
                    elif c == '\\':
                        esc = True
                    elif c == in_s:
                        in_s = None
                else:
                    if c == '"' or c == "'":
                        in_s = c
                    elif c == '[':
                        depth += 1
                    elif c == ']':
                        depth -= 1
                        if depth == 0:
                            return start_idx, i + 1
                i += 1
            return None

        def parse_numbers_from_bracket(s: str):
            # find floats/ints in string s
            nums = re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", s)
            return [float(x) for x in nums]

        # search for x/y/z tokens globally and try to parse
        x_pos = [m.start() for m in re.finditer(r'(?:(?:"x"|\'x\'|\bx\b)\s*:\s*\[)', text)]
        parsed = None
        for pos in x_pos:
            # pos points at the start of the '[' (via the regex group offset), but regex returns start of whole match
            # find actual bracket char after pos
            br_idx = text.find('[', pos)
            if br_idx == -1:
                continue
            span = find_bracket_span(br_idx)
            if not span:
                continue
            s, e = span
            x_nums = parse_numbers_from_bracket(text[s:e])
            # look for nearby y and z
            window_start = max(0, s - 2000)
            window_end = min(len(text), e + 2000)
            window = text[window_start:window_end]
            def parse_key_in_window(key: str):
                mm = re.search(rf'(?:(?:"{key}"|\'{key}\'|\b{key}\b)\s*:\s*(\[))', window)
                if not mm:
                    return None
                abs_idx = window_start + mm.start(1)
                sp = find_bracket_span(abs_idx)
                if not sp:
                    return None
                ss, ee = sp
                return parse_numbers_from_bracket(text[ss:ee])

            y_nums = parse_key_in_window('y')
            z_nums = parse_key_in_window('z')
            if y_nums is not None and z_nums is not None and len(x_nums) == len(y_nums) == len(z_nums) and len(x_nums) > 0:
                parsed = [{ 'x': x_nums, 'y': y_nums, 'z': z_nums }]
                break

        if parsed is not None:
            data = parsed

    if data is None:
        # gather a short debug snippet around the last Plotly anchor to help
        # troubleshooting when running on user HTML files.
        anchors_debug = ["Plotly.newPlot", "Plotly.react", "Plotly.plot", "newPlot"]
        last_pos = -1
        for a in anchors_debug:
            p = text.rfind(a)
            if p > last_pos:
                last_pos = p
        snippet = None
        if last_pos != -1:
            snippet = text[max(0, last_pos - 120): last_pos + 280]
        raise RuntimeError(f"Couldn't locate Plotly data in {html_path} with any heuristic. Debug snippet (truncated):\n{snippet if snippet is not None else '<none>'}")

    if not isinstance(data, list):
        raise RuntimeError(f"Plotly data not a list in {html_path}")

    # pick first trace-like dict containing coordinates
    trace = None
    for t in data:
        if isinstance(t, dict) and any(k in t for k in ('x', 'y', 'z')):
            trace = t
            break
    if trace is None:
        # fallback: first dict
        for t in data:
            if isinstance(t, dict):
                trace = t
                break
    if trace is None:
        raise RuntimeError(f"No trace-like object found in Plotly data in {html_path}")

    x = np.array(trace.get('x', []), dtype=float)
    y = np.array(trace.get('y', []), dtype=float)
    z = np.array(trace.get('z', []), dtype=float)

    # Colors may be in marker.color as list of 'rgb(r,g,b)' strings or arrays
    marker = trace.get('marker', {}) if isinstance(trace.get('marker', {}), dict) else {}
    colors = marker.get('color', None)

    rgb_list = []
    if isinstance(colors, list) and len(colors) == len(x):
        for c in colors:
            if isinstance(c, str) and c.startswith('rgb'):
                nums = c[c.find('(')+1:c.find(')')].split(',')
                try:
                    rgb_list.append(tuple(int(n) for n in nums))
                except Exception:
                    rgb_list.append((255,255,255))
            elif isinstance(c, (list, tuple)) and len(c) >= 3:
                try:
                    rgb_list.append(tuple(int(round(255 * float(v))) if float(v) <= 1.0 else int(v) for v in c[:3]))
                except Exception:
                    rgb_list.append((255,255,255))
            else:
                try:
                    v = float(c)
                    iv = int(round(255 * v)) if v <= 1.0 else int(v)
                    rgb_list.append((iv, iv, iv))
                except Exception:
                    rgb_list.append((255,255,255))
    else:
        rgb_list = [(200, 200, 200)] * len(x)

    return x, y, z, rgb_list


def make_figure_xyzrgb(x: np.ndarray, y: np.ndarray, z: np.ndarray, rgb_list: List[Tuple[int,int,int]], marker_size: int = 2) -> go.Figure:
    colors = [f'rgb({r},{g},{b})' for r, g, b in rgb_list]
    fig = go.Figure(data=[
        go.Scatter3d(
            x=x, y=y, z=z,
            mode='markers',
            marker=dict(size=marker_size, color=colors, opacity=0.9),
        )
    ])
    # default layout
    fig.update_layout(scene=dict(aspectmode='data'))
    return fig


def render_frames_with_matplotlib(x: np.ndarray, y: np.ndarray, z: np.ndarray, rgb_list: List[Tuple[int,int,int]], angles: np.ndarray, frame_dir: Path, size: Tuple[int,int], radius: float, matplotlib_dist: float = None, marker_size: int = 2):
    """Render frames using matplotlib as a fallback when kaleido/plotly image export is unavailable.

    Saves PNGs into frame_dir named frame_%06d.png
    """
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
        from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
    except Exception as e:
        raise RuntimeError(f"Matplotlib fallback unavailable: {e}")

    pts = np.stack([x, y, z], axis=1)
    centroid = pts.mean(axis=0)
    # radius is provided by caller (max_dist * cam_zoom)
    xmin, xmax = centroid[0] - radius, centroid[0] + radius
    ymin, ymax = centroid[1] - radius, centroid[1] + radius
    zmin, zmax = centroid[2] - radius, centroid[2] + radius

    # prepare colors as 0..1 floats
    colors = np.array(rgb_list, dtype=float) / 255.0

    dpi = 100
    figsize = (size[0] / dpi, size[1] / dpi)

    for i, ang in enumerate(tqdm(angles, desc=f"MATPLOTLIB Rendering")):
        # ensure white background and no axes
        fig = plt.figure(figsize=figsize, dpi=dpi, facecolor='white')
        ax = fig.add_subplot(111, projection='3d')

        ax.scatter(x, y, z, c=colors, s=marker_size)

        ax.set_xlim(xmin, xmax)
        ax.set_ylim(ymin, ymax)
        ax.set_zlim(zmin, zmax)

        # view: convert angle (radians) to azimuth degrees
        azim = np.degrees(ang)
        elev = 20
        # adjust Matplotlib camera distance (ax.dist) proportional to cam_zoom
        try:
            if matplotlib_dist is not None:
                ax.dist = float(matplotlib_dist)
            else:
                max_dist_local = np.max(np.linalg.norm(pts - centroid[None, :], axis=1))
                cam_zoom_local = radius / max_dist_local if max_dist_local > 0 else 1.0
                # map default cam_zoom=1.25 to default ax.dist ~10; scale linearly but allow smaller values
                ax.dist = float(max(1.0, 10.0 * (cam_zoom_local / 1.25)))
        except Exception:
            pass
        ax.view_init(elev=elev, azim=azim)

        ax.set_box_aspect((xmax - xmin, ymax - ymin, zmax - zmin))
        ax.axis('off')

        out_png = frame_dir / f"frame_{i:06d}.png"
        fig.savefig(str(out_png), bbox_inches='tight', pad_inches=0, facecolor='white')
        plt.close(fig)


def render_frames_with_open3d(x: np.ndarray, y: np.ndarray, z: np.ndarray, rgb_list: List[Tuple[int,int,int]], angles: np.ndarray, frame_dir: Path, size: Tuple[int,int], radius: float, matplotlib_dist: float = None):
    """Render frames using Open3D offscreen renderer.

    Background will be white. Saves PNGs into frame_dir named frame_%06d.png
    """
    try:
        import open3d as o3d
    except Exception as e:
        raise RuntimeError(f"Open3D not available: {e}")

    pts = np.stack([x, y, z], axis=1)
    centroid = pts.mean(axis=0)
    # radius is provided by caller (max_dist * cam_zoom)

    # prepare pointcloud
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(pts)
    colors = np.array(rgb_list, dtype=float) / 255.0
    pcd.colors = o3d.utility.Vector3dVector(colors)

    width, height = int(size[0]), int(size[1])

    # OffscreenRenderer available in Open3D >= 0.12
    saved = []
    try:
        renderer = o3d.visualization.rendering.OffscreenRenderer(width, height)
        scene = renderer.scene
        # set white background
        renderer.scene.set_background([1.0, 1.0, 1.0, 1.0])
        mat = o3d.visualization.rendering.MaterialRecord()
        mat.shader = 'defaultUnlit'
        scene.add_geometry("pcd", pcd, mat)

        up = [0.0, 0.0, 1.0]
        for i, ang in enumerate(tqdm(angles, desc="Open3D Rendering")):
            eye = [centroid[0] + radius * math.cos(ang),
                   centroid[1] + radius * math.sin(ang),
                   centroid[2] + radius * 0.25]
            # look_at(center, eye, up)
            scene.camera.look_at(centroid.tolist(), eye, up)
            img = renderer.render_to_image()
            # convert to numpy array and save via PIL
            try:
                img_arr = np.asarray(img)
            except Exception:
                # fallback conversion
                img = o3d.geometry.Image(img)
                img_arr = np.asarray(img)
            # img_arr is HxWx3 or HxWx4; convert to uint8
            from PIL import Image
            im = Image.fromarray(img_arr.astype('uint8'))
            out_png = frame_dir / f"frame_{i:06d}.png"
            im.save(str(out_png))
            saved.append(out_png)
        try:
            renderer.release()
        except Exception:
            pass
    except AttributeError:
        # older Open3D may not have OffscreenRenderer — fall back to visualizer (not headless)
        raise RuntimeError("Open3D installed but OffscreenRenderer unavailable (requires a newer Open3D).")
    except Exception:
        # on any other failure during Open3D rendering, remove any partial frames then re-raise
        for f in saved:
            try:
                f.unlink()
            except Exception:
                pass
        try:
            renderer.release()
        except Exception:
            pass
        raise


def render_rotating_video_from_html(html_file: Path, out_dir: Path, num_frames: int = 60, fps: int = 15, size: Tuple[int,int]=(1200,800), use_matplotlib: bool = False, use_open3d: bool = False, cam_zoom: float = 1.25, max_points: int = 100000, matplotlib_dist: float = None, marker_size: int = 2) -> Path:
    """Extract point cloud from one HTML and render rotating video frames, then assemble to mp4.

    cam_zoom controls camera distance as radius = max_dist * cam_zoom (default 1.25).
    Returns path to generated mp4 file.
    """
    # Prefer sidecar .npz if present (written by visualize_zarr_pointcloud.py)
    npz_path = html_file.with_suffix('.npz')
    if npz_path.exists():
        try:
            with np.load(str(npz_path)) as arr:
                x = arr['x']
                y = arr['y']
                z = arr['z']
                if 'rgb' in arr:
                    rgb_arr = arr['rgb']
                    # normalize into list of (r,g,b) ints
                    rgb_list = [tuple(int(v) for v in rgb_arr[i]) for i in range(len(x))]
                else:
                    rgb_list = [(200, 200, 200)] * len(x)
        except Exception:
            # fallback to HTML parsing if sidecar load fails
            x, y, z, rgb_list = extract_plotly_data_from_html(html_file)
    else:
        x, y, z, rgb_list = extract_plotly_data_from_html(html_file)

    pts = np.stack([x, y, z], axis=1)

    # compute centroid and radius
    centroid = pts.mean(axis=0)
    max_dist = np.max(np.linalg.norm(pts - centroid[None, :], axis=1))
    radius = max(1.0, float(max_dist) * float(cam_zoom))

    # optionally downsample very large point clouds for faster matplotlib rendering
    npts = len(x)
    if max_points is not None and npts > int(max_points):
        rng = np.random.default_rng(0)
        idx = rng.choice(npts, size=int(max_points), replace=False)
        x = x[idx]
        y = y[idx]
        z = z[idx]
        try:
            rgb_arr = np.array(rgb_list)
            rgb_list = [tuple(int(v) for v in rgb_arr[i]) for i in range(len(x))]
        except Exception:
            rgb_list = rgb_list[:len(x)]

    # rgb variable may be either rgb_list (from sidecar) or previous name; ensure we pass rgb_list
    fig = make_figure_xyzrgb(x, y, z, rgb_list, marker_size=marker_size)
    # prepare output frame dir
    out_dir.mkdir(parents=True, exist_ok=True)
    base_name = html_file.stem
    frame_dir = out_dir / f"{base_name}_frames"
    frame_dir.mkdir(parents=True, exist_ok=True)

    angles = np.linspace(0, 2 * math.pi, num_frames, endpoint=False)

    # If user requested Open3D, try it first
    if use_open3d:
        try:
            render_frames_with_open3d(x, y, z, rgb_list, angles, frame_dir, size, radius, matplotlib_dist)
            opened_with_open3d = True
        except Exception as e:
            print(f"Open3D rendering failed: {e}. Falling back to other renderers.")
            # remove any partial frames produced by Open3D to avoid mixed-styles
            try:
                for f in frame_dir.glob('frame_*.png'):
                    try:
                        f.unlink()
                    except Exception:
                        pass
            except Exception:
                pass
            opened_with_open3d = False
        if opened_with_open3d:
            # assemble with ffmpeg and return
            out_mp4 = out_dir / f"{base_name}.mp4"
            cmd = [
                'ffmpeg', '-y', '-framerate', str(fps),
                '-i', str(frame_dir / 'frame_%06d.png'),
                '-c:v', 'libx264', '-pix_fmt', 'yuv420p', str(out_mp4)
            ]
            subprocess.run(cmd, check=True)
            return out_mp4

    # If user requested matplotlib, skip Plotly/Kaleido entirely
    if use_matplotlib:
        render_frames_with_matplotlib(x, y, z, rgb_list, angles, frame_dir, size, radius, matplotlib_dist, marker_size=marker_size)
    else:
        # Try Plotly/Kaleido rendering first; on failure fall back to matplotlib-based renderer
        use_matplotlib_fallback = False
        for i, ang in enumerate(tqdm(angles, desc=f"Rendering {html_file.name}")):
            eye = dict(x=centroid[0] + radius * math.cos(ang),
                       y=centroid[1] + radius * math.sin(ang),
                       z=centroid[2] + radius * 0.25)
            camera = dict(eye=eye)
            fig.update_layout(scene_camera=camera)

            out_png = frame_dir / f"frame_{i:06d}.png"
            # attempt to write with plotly/kaleido
            try:
                fig.write_image(str(out_png), width=size[0], height=size[1], engine='kaleido')
            except Exception as e:
                # fallback to matplotlib to render all frames
                use_matplotlib_fallback = True
                print(f"Plotly/Kaleido render failed: {e}. Falling back to matplotlib renderer.")
                # cleanup any partial frames
                for f in frame_dir.glob('frame_*.png'):
                    try:
                        f.unlink()
                    except Exception:
                        pass
                break

        if use_matplotlib_fallback:
            render_frames_with_matplotlib(x, y, z, rgb_list, angles, frame_dir, size, radius, matplotlib_dist, marker_size=marker_size)

    # assemble with ffmpeg
    out_mp4 = out_dir / f"{base_name}.mp4"
    cmd = [
        'ffmpeg', '-y', '-framerate', str(fps),
        '-i', str(frame_dir / 'frame_%06d.png'),
        '-c:v', 'libx264', '-pix_fmt', 'yuv420p', str(out_mp4)
    ]
    subprocess.run(cmd, check=True)

    return out_mp4


def main():
    parser = argparse.ArgumentParser(description='Convert Plotly HTML pointclouds to rotating MP4s')
    parser.add_argument('--input-dir', type=str, required=True, help='Directory containing HTML files')
    parser.add_argument('--output-dir', type=str, required=True, help='Output directory for videos and frames')
    parser.add_argument('--num-frames', type=int, default=60, help='Number of frames per rotation')
    parser.add_argument('--fps', type=int, default=15, help='Frames per second in output MP4')
    parser.add_argument('--size', type=int, nargs=2, default=[1200,800], help='Output image size W H')
    parser.add_argument('--force-matplotlib', action='store_true', help='Force use of matplotlib renderer instead of Plotly/Kaleido')
    parser.add_argument('--use-open3d', action='store_true', help='Prefer Open3D offscreen renderer for frames (white background)')
    parser.add_argument('--cam-zoom', type=float, default=1.25, help='Camera distance multiplier (radius = max_dist * cam_zoom). Lower -> camera closer.')
    parser.add_argument('--max-points', type=int, default=100000, help='If pointcloud has more points than this, randomly downsample to this many for rendering (matplotlib).')
    parser.add_argument('--matplotlib-dist', type=float, default=None, help='Directly set Axes3D.dist for Matplotlib renderer (smaller -> closer).')
    parser.add_argument('--marker-size', type=int, default=2, help='Marker size to use for points in both Matplotlib and Plotly renderers')
    args = parser.parse_args()

    input_path = Path(args.input_dir)
    output_path = Path(args.output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    html_files = sorted([p for p in input_path.iterdir() if p.suffix.lower() == '.html'])
    if not html_files:
        print(f"No HTML files found in {input_path}")
        return

    print(f"Found {len(html_files)} HTML files, rendering videos to: {output_path}")

    for html_file in html_files:
        try:
            mp4 = render_rotating_video_from_html(
                html_file, output_path, num_frames=args.num_frames, fps=args.fps,
                size=tuple(args.size), use_matplotlib=args.force_matplotlib, use_open3d=args.use_open3d, cam_zoom=args.cam_zoom, max_points=args.max_points, matplotlib_dist=args.matplotlib_dist, marker_size=args.marker_size)
            print(f"Created video: {mp4}")
        except Exception as e:
            print(f"Failed for {html_file.name}: {e}")


if __name__ == '__main__':
    main()
